Add cd commands
OpenLiberty/guide-kubernetes-intro pull request #149
Opened 2020-10-02 14:29 UTC by griffinhadfield

Addressing https://github.com/openliberty/guides-common/issues/514

2020-10-05 21:30 UTC, tt-le approved these changes
LGTM checked on LGDEV

2020-10-06 17:09 UTC, tt-le requested changes
Upon further thought,  I think we should reword the text preceding the `cd start` command. Right now it seems like we're asking the user to navigate to the `start` directory and running `cd start` again.

2020-10-06 21:03 UTC, griffinhadfield commented
@tt-le I have changed that line to the following:

> Navigate to the `start` directory build the applications by running the following commands:

What do you think?

2020-10-07 13:35 UTC, tt-le requested changes

2020-10-07 13:35 UTC, tt-le commented on README.adoc
> +Navigate to the `start` directory build the applications by running the following commands:
@griffinhadfield minor mistake
> Navigate to the `start` directory **and** build the applications by running the following commands:

2020-10-07 17:49 UTC, griffinhadfield commented on README.adoc
> +Navigate to the `start` directory build the applications by running the following commands:
Good catch, thank you. Its now fixed

2020-10-07 18:06 UTC, tt-le approved these changes
LGTM

2020-10-07 18:42 UTC, merged