Rolling update
OpenLiberty/guide-kubernetes-intro pull request #211
Opened 2022-05-06 19:45 UTC by t27gupta

2022-05-09 18:26 UTC, gkwan-ibm requested changes
License year should be `2022`

2022-05-27 21:58 UTC, gkwan-ibm requested changes
@t27gupta 
- fix the test failure
- add hotspot to rollingUpdate -> "The `rollingUpdate` configuration..."
  - highlight all following lines for both services
```
  -   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
```
- "...has two attributes within it which are `maxUnavailable` and `maxSurge`. " ->  "...has two attributes. "
- "maxUnavailable refers ..." -> "The `maxUnavailable` attribute refers ..."
  - hotspot `maxUnavailable`
- "...the the number ", remove a "the"
- "Similarly, maxSurge refers..." -> "Similarly, the `maxSurge` attribute refers..."
  - hotspot `maxSurge`
- rewrite "The readiness check for both Inventory and System has already been provided within the health directory of each."
   - a statement to explain why need the readiness check
   - a statement tells the readiness check for both services are provided
   - hotspot should highlight all following lines
```
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
```
- "The remaining startup and liveness health checks can be found in the [Kubernetes-microprofile-health](https://openliberty.io/guides/kubernetes-microprofile-health.html) guide." -> "You can learn more about how to use health checks in Kubernetes, check out the [Kubernetes-microprofile-health](https://openliberty.io/guides/kubernetes-microprofile-health.html) guide."

2022-05-30 14:00 UTC, gkwan-ibm commented
Readiness checklist:
- [ ] verify on the guides development site VM
- [ ] verify end-to-end locally if the source has change
- [ ] verify end-to-end on cloud-hosted if apply
- [ ] PR test pass

2022-05-31 17:08 UTC, gkwan-ibm commented
hi @t27gupta 

- add hotspot to the rollingUpdate word -> "The `rollingUpdate` configuration..."
  - highlight all following lines for both services
```
  -   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
```
- "...attributes maxUnavailable and maxSurge. " backtick both attributes as "...attributes `maxUnavailable` and `maxSurge`."
- the `readiness check` hotspot no need to highlight following lines
```
        env:
        - name: SYS_APP_HOSTNAME
          value: system-service
```

2022-06-02 13:31 UTC, gkwan-ibm commented
hi @t27gupta
- "Rolling Update refers to... " -> "Rolling update refers to ..."
- "Update the yaml as follows to add the rollingUpdate configuration." -> "Update the yaml file as follows to add the `rollingUpdate` configuration."
    - add "file" after yaml and backtick "rollingUpdate"
- "The `readiness check` allows third party applications and services to know whether the service is ready to handle requests. " -> "The `readinessProbe` configuration allows Kubernetes to know whether the service is ready to handle requests." 
  -  `readinessProbe` highlights same as `readiness check`
- "A readiness health check has already been implemented for the inventory and system services." -> "The readiness health check classes for the `/health/ready` endpoint to the `inventory` and `system` services are provided for you."
- "You can learn more about..." -> "If you want to learn more about..."

2022-06-02 20:42 UTC, dmuelle reviewed
ID review- a few minor suggestions

2022-06-02 20:42 UTC, dmuelle commented on README.adoc
> +Rolling update refers to continually installing Kubernetes patches without disrupting the availability of the deployed applications. Without continuous updates, a Kubernetes cluster will be susceptib
```suggestion
Without continuous updates, a Kubernetes cluster is susceptible to a denial of a service attack. Rolling updates continually install Kubernetes patches without disrupting the availability of the deployed applications. Update the yaml file as follows to add the `rollingUpdate` configuration. 
```

2022-06-02 20:42 UTC, dmuelle commented on README.adoc
> +The [hotspot=rolling1 hotspot=rolling2]`rollingUpdate` configuration has two attributes `maxUnavailable` and `maxSurge`. The [hotspot=maxUnavailable1 hotspot=maxUnavailable2]`maxUnavailable` attribut
```suggestion
The [hotspot=rolling1 hotspot=rolling2]`rollingUpdate` configuration has two attributes, `maxUnavailable` and `maxSurge`. The [hotspot=maxUnavailable1 hotspot=maxUnavailable2]`maxUnavailable` attribute specifies the the maximum number of Kubernetes pods that can be unavailable during the update process. Similarly, the [hotspot=maxSurge1 hotspot=maxSurge2]`maxSurge` attribute specifies the maximum number of additional pods that can be created during the update process.
```

2022-06-02 20:49 UTC, dmuelle approved these changes
LGTM, thanks

2022-06-02 20:56 UTC, gkwan-ibm approved these changes

2022-06-02 20:56 UTC, merged